[api]
prefix='/api'

[db]
host="localhost"
port=3306
username="root"
password="root"
database="taco"
synchronize=true
autoLoadEntities=true

[bcrypt]
salt="VG!ha(Rwa_xurpzyB4"
cost=12

[jwt]
expire='7d'
publicKeyPath="./keys/key.pub"
privateKeyPath="./keys/key.pri"

[redis]
nodes=[{host="127.0.0.1",port=6384}]