[api]
prefix='/api'
[asset]
[asset.avatar]
fs_path="./public"
ext=".png"

[db]
host="mysql"
port=3306
username="root"
password="root"
database="taco"
synchronize=true
autoLoadEntities=true

[bcrypt]
salt="VG!ha(Rwa_xurpzyB4"
cost=12

[jwt]
expire='7d'
publicKeyPath="./keys/key.pub"
privateKeyPath="./keys/key.pri"
[redis]
nodes=[{host="redis-node-6",port=6384}]
# nodes=[{host="127.0.0.1",port=6384}]
