version: '3'

x-redis: &common
  image: redis
  restart: on-failure
  command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

services:
  api:
    image: taco:beta
    volumes:
      - ./keys:/usr/taco/keys
      - ./config.toml:/usr/taco/config.toml
      - ./public:/usr/taco/public
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - node-1
      - node-2
      - node-3
      - node-4
      - node-5
      - node-6

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=taco
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./mysql:/var/lib/mysql/
  node-1:
    <<: *common
    container_name: redis-node-1
    volumes:
      - ./redis-cluster-data/node1/data:/data
      - ./redis-cluster-data/node1/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
      - 16379:16379

  node-2:
    <<: *common
    container_name: redis-node-2
    volumes:
      - ./redis-cluster-data/node2/data:/data
      - ./redis-cluster-data/node2/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6380:6380
      - 16380:16380

  node-3:
    <<: *common
    container_name: redis-node-3
    volumes:
      - ./redis-cluster-data/node3/data:/data
      - ./redis-cluster-data/node3/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6381:6381
      - 16381:16381

  node-4:
    <<: *common
    container_name: redis-node-4
    volumes:
      - ./redis-cluster-data/node4/data:/data
      - ./redis-cluster-data/node4/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6382:6382
      - 16382:16382

  node-5:
    <<: *common
    container_name: redis-node-5
    volumes:
      - ./redis-cluster-data/node5/data:/data
      - ./redis-cluster-data/node5/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6383:6383
      - 16383:16383

  node-6:
    <<: *common
    container_name: redis-node-6
    volumes:
      - ./redis-cluster-data/node6/data:/data
      - ./redis-cluster-data/node6/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6384:6384
      - 16384:16384

networks:
  redis-cluster:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/24