FROM node:20.8.0-alpine

WORKDIR /usr/taco/account
ADD . .

RUN npm install pnpm -g && \
    pnpm install --production && \
    pnpm build account

VOLUME [ "/usr/taco/account" ]
ENV ACCOUNT_SERVICE_URL="0.0.0.0:5000"
EXPOSE 5000

CMD [ "node", "dist/apps/account/main.js" ]