FROM node:20.8.0-alpine

WORKDIR /usr/taco/user
ADD . .

RUN npm install pnpm -g && \
    pnpm install --production && \
    pnpm build user
VOLUME [ "/usr/taco/reputation" ]
ENV USER_SERVICE_URL=0.0.0.0:9000
EXPOSE 9000

CMD [ "node", "dist/apps/user/main.js" ]