FROM node as dev

WORKDIR /usr/taco/user
ADD . .

RUN npm install pnpm -g && \
    pnpm install --production && \
    pnpm build user

ENV USER_SERVICE_URL=localhost:9000
EXPOSE 9000

CMD [ "node", "dist/apps/user/main.js" ]