FROM node:20.8.0-alpine

WORKDIR /usr/taco/token
ADD . .

RUN npm install pnpm -g && \
    pnpm install --production && \
    pnpm build token
VOLUME [ "/usr/taco/reputation" ]
ENV TOKEN_SERVICE_URL=0.0.0.0:7000
EXPOSE 7000

CMD [ "node", "dist/apps/token/main.js" ]