FROM node:20.8.0-alpine

WORKDIR /usr/taco/friends
ADD . .

RUN npm install pnpm -g && \
    pnpm install --production && \
    pnpm build friends
VOLUME [ "/usr/taco/friends" ]
ENV FRIEND_SERVICE_URL=localhost:10000
EXPOSE 10000

CMD [ "node", "dist/apps/friends/main.js" ]