FROM node:20.8.0-alpine

WORKDIR /usr/taco/reputation
ADD . .

RUN npm install pnpm -g && \
    pnpm install --production && \
    pnpm build reputation
VOLUME [ "/usr/taco/reputation" ]
ENV REPUTATION_SERVICE_URL=0.0.0.0:6000
EXPOSE 6000

CMD [ "node", "dist/apps/reputation/main.js" ]