FROM node:20.8.0-alpine

WORKDIR /usr/taco/notice
ADD . .

RUN npm install pnpm -g && \
    pnpm install --production && \
    pnpm build notice
VOLUME [ "/usr/taco/notice" ]
ENV NOTICE_SERVICE_URL=0.0.0.0:11000
EXPOSE 11000

CMD [ "node", "dist/apps/notice/main.js" ]