name: Test

on: [pull_request, workflow_dispatch]

env:
    CI: true
    REDIS_MODE: standalone

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                version: 9
                run_install: false
            - uses: actions/setup-node@v4
              name: Setup Node.js
              with:
                cache: 'pnpm'
                node-version: 20.x
            - run: pnpm i 
            - run: node setup.js
            - run: pnpm test
              env:
                CI: true
                REDIS_MODE: standalone

